version: "3.8"
services:
  web:
    container_name: nad-ch-dev-local
    image: nad-ch-dev-local
    ports:
      - "8080:5000"
    depends_on:
      - postgres
      - redis
      - storage
      - flower
    build:
      context: .
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app:z
      - /app/nad_ch/controllers/web/node_modules:z
      - /app/nad_ch/controllers/web/dist:z

  postgres:
    container_name: postgres
    image: postgres:18
    ports:
      - "5432:5432"
    volumes:
      - ${VOLUMES}/nad_pgvol/data:/var/lib/postgresql:z
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    env_file:
      - .env

  storage:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ${VOLUMES}/s3_miniovol/storage:/storage:z
    env_file:
      - .env
    command: server /storage --console-address :9001

  flower:
    container_name: flower
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER=redis://redis:6379/0
